In [1]:
import numpy as np

### 1 创建和保存 Numpy ndarrays
#### 1.1 创建 numpy ndarrays
#### 1.2 保存 numpy array 

In [19]:
# 1.1
# 2Darray
x = np.array([[1, 2, 3.2, 4, 5], [6, 7, 8, 9, 10]], dtype=np.int64)
print(x.shape)
print(x.size)
print(x.dtype)

(2, 5)
10
int64


In [21]:
# 1.2
# 保存 ndarray 到文件
np.save('my_array', x)
# 从文件中读取 array
y = np.load('my_array.npy')
print(y)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


### 2 使用内置函数创建 arrays
#### 2.1 `np.zeros(size)`
#### 2.2 `np.ones(size)`
#### 2.3 `np.full(size, num)`
#### 2.4 `np.eye(num)`
单位矩阵
#### 2.5 `np.diag(num_list)`
对角矩阵
#### 2.6 `np.arange(start, end, step)`
#### 2.7 `np.linspace(start, end, N=50, endpoint = True)`
#### 2.8 `np.random.random(size)`
#### 2.9 `np.random.randint(start, end, size)`
#### 2.10 `np.random.normal(mean, standard deviation, size=shape)`

In [26]:
# 2.1
zeros_array = np.zeros((2, 3))
# 2.2
ones_array = np.ones((3, 2))
# 2.3
nums_array = np.full((2, 3), 6)
# 2.4 单位矩阵
eyes_array = np.eye(6)
# 2.5 对角矩阵
diags_array = np.diag([10, 20, 30, 40])
print(zeros_array)
print(ones_array)
print(nums_array)
print(eyes_array)
print(diags_array)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[6 6 6]
 [6 6 6]]
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]
[[10  0  0  0]
 [ 0 20  0  0]
 [ 0  0 30  0]
 [ 0  0  0 40]]


In [28]:
# 2.6 
arange_array = np.arange(2, 10, 2)
print(arange_array)

[2 4 6 8]


In [36]:
# 2.7
linspace_arrge = np.linspace(0, 100, 20, endpoint=True, dtype=np.int64).reshape(4, 5)
print(linspace_arrge)

[[  0   5  10  15  21]
 [ 26  31  36  42  47]
 [ 52  57  63  68  73]
 [ 78  84  89  94 100]]


In [37]:
# 2.8
# [0.0, 1.0)
random_array = np.random.random((3, 3))
print(random_array)

[[0.04963467 0.67799726 0.93673986]
 [0.99535029 0.5145348  0.96063178]
 [0.52763841 0.2636562  0.10014667]]


In [40]:
# 2.9
# [start, end)
randint_array = np.random.randint(6, 8, (3, 3))
print(randint_array)

[[6 6 6]
 [6 6 7]
 [7 6 6]]


In [46]:
# 2.10
# 正态分布
normal_array = np.random.normal(0, 1, size=(3, 3))
print(normal_array)

[[ 1.00674909 -0.40365721 -0.3514684 ]
 [ 0.29534814 -0.36189898 -0.03349199]
 [-0.15115684 -1.73481949  0.63495654]]


In [49]:
X = np.linspace(2, 32, 16).reshape((4, 4))
X

array([[ 2.,  4.,  6.,  8.],
       [10., 12., 14., 16.],
       [18., 20., 22., 24.],
       [26., 28., 30., 32.]])

### 3 添加或删除 array 中的元素
#### 3.1 删除元素
`np.delete(ndarray, elements, axis)`
#### 3.2 添加元素
`np.append(ndarray, elements, axis)`
#### 3.3 插入元素
`np.insert(ndarray, index, elements, axis)`
#### 3.4 array 堆叠
##### 3.4.1 垂直堆叠
`np.vstack((array, array))`
##### 3.4.2 水平堆叠
`np.hstack((arrat, array))`

In [51]:
# 3.1
x = np.array([[1, 2, 3], 
             [4, 5, 6], 
             [7, 8, 9]])
x = np.delete(x, 0, 0)
# 索引
y = np.delete(x, [0, 2], 1)
print(x)
print(y)

[[4 5 6]
 [7 8 9]]
[[5]
 [8]]


In [63]:
# 3.2
x = np.array([[1, 2, 3], 
             [4, 5, 6], 
             [7, 8, 9]])
# 二维元素
x = np.append(x, [[10, 11, 12]], 0)
y = np.append(x, [[10], [11], [12], [13]], 1)
print(x)
print(y)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3 10]
 [ 4  5  6 11]
 [ 7  8  9 12]
 [10 11 12 13]]


In [66]:
# 3.3
x = np.array([[1, 2, 3], 
             [4, 5, 6], 
             [7, 8, 9]])
y = np.insert(x, 1, [6, 6, 6], 0)
print(y)
x = np.insert(x, 1, [6, 6, 6], 1)
print(x)

[[1 2 3]
 [6 6 6]
 [4 5 6]
 [7 8 9]]
[[1 6 2 3]
 [4 6 5 6]
 [7 6 8 9]]


In [70]:
# 3.4
# 3.4.1
# 1D
x = np.array([1,2])
# 2D
y = np.array([[3, 4],
             [5, 6]])
z = np.vstack((x, y))
print(z)
# 3.4.2
w = np.hstack((x.reshape(2, 1), y))
print(w)

[[1 2]
 [3 4]
 [5 6]]
[[1 3 4]
 [2 5 6]]


### 4 切片
切片不会在内存中创建新的 array，切片元素的改变会导致原始数组元素的改变 
#### 4.1 将切片复制到新的 array 中
`np.copy(array)`
#### 4.2 按对角线提取元素
`np.diag(array, K=0)`
#### 4.3 提取 array 中唯一的元素
`np.unique(array)`

In [86]:
# 4.1
x = np.arange(25).reshape((5, 5))
y = np.copy(x[[1,2],1:4])
y[0][0] = 0
print(x)
print(y)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[ 0  7  8]
 [11 12 13]]


In [89]:
# 4,2
print(np.diag(x))
print(np.diag(x, 1))
print(np.diag(x, -3))

[ 0  6 12 18 24]
[ 1  7 13 19]
[15 21]


In [92]:
# 4,3
x = np.array([[2, 3, 4],
            [5, 2, 3], 
            [4, 3, 2]])
print(np.unique(x))

[2 3 4 5]


### 5 布尔索引、array 比较与排序
#### 5.1 布尔索引
#### 5.2 比较
`np.intersect1d(x, y)  # 并集`      
`np.union1d(x, y)  # 交集`    
`np.setdiff1d(x, y)  # 在 x 中但不在 y 中`
#### 5.3 排序
#### 5.3.1 1d 排序
##### 5.3.1.1 `np.sort(array)  # 不改变内存`
##### 5.3.1.2 `array.sort()  # 改变内存`
##### 5.3.1.3 `np.unique(x.sort())  # 去除重复值后排序`
#### 5.3.2 2d 排序

In [96]:
# 5.1
x = np.arange(25).reshape((5, 5))
print(x)
print(x[(x>10) & (x<20)])
x[x > 10] = -1
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[11 12 13 14 15 16 17 18 19]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]]


In [97]:
# 5.2
x = np.array([1,2,3,4,5])
y = np.array([6,7,2,8,4])
x_and_y = np.intersect1d(x ,y)
x_or_y = np.union1d(x, y)
x_diff_y = np.setdiff1d(x, y)
print(x_and_y)
print(x_or_y)
print(x_diff_y)

[2 4]
[1 2 3 4 5 6 7 8]
[1 3 5]


In [105]:
# 5.3
# 5.3.1.1
x = np.random.randint(1, 11, (10))
print(x)
y = np.sort(x)
print(y)
# 5.3.1.2
x.sort()
print(x)

[ 5  4  9  5  9  3  3 10  2  4]
[ 2  3  3  4  4  5  5  9  9 10]
[ 2  3  3  4  4  5  5  9  9 10]


In [110]:
# 5.3.1.3
x = np.random.randint(1, 11, (10))
print(x)
x = np.unique(x)
x.sort()
print(x)

[10 10  2  3  6  9  4 10  9  6]
[ 2  3  4  6  9 10]


In [115]:
# 5.3.2
x = np.random.randint(1, 11, (5, 5))
print(x)
print(np.sort(x, axis=0))
print(np.sort(x, axis=1))

[[ 4  7  3  7  4]
 [ 4  7  5  6  8]
 [10 10  7  7  7]
 [ 5  2  8  6  4]
 [ 1  3  3  3 10]]
[[ 1  2  3  3  4]
 [ 4  3  3  6  4]
 [ 4  7  5  6  7]
 [ 5  7  7  7  8]
 [10 10  8  7 10]]
[[ 3  4  4  7  7]
 [ 4  5  6  7  8]
 [ 7  7  7 10 10]
 [ 2  4  5  6  8]
 [ 1  3  3  3 10]]


### 6 算数运算和广播
#### 6.1 算数运算
`np.exp(array)`      
`np.sqrt(array)  # 开方`     
`np.power(array, n)`
#### 6.2 统计
`array.mean(axis)`
`array.sum(axis)`
`array.std(axis)`
`array.max(axis)`
`array.min(axis)`
`np.median(array, axis)  # 中位数`
#### 6.3 广播

In [121]:
# 6.1
x = np.array([1, 2, 3, 4])
print(np.exp(x))
print(np.sqrt(x))
print(np.power(x ,3))

[ 2.71828183  7.3890561  20.08553692 54.59815003]
[1.         1.41421356 1.73205081 2.        ]
[ 1  8 27 64]


In [135]:
# 6.2
x = np.array([[1, 2], 
            [3, 4]])
print(x.mean(), x.mean(axis=0), x.mean(axis=1))
print(x.sum(), x.sum(axis=0), x.sum(axis=1))
print(x.std(), x.std(axis=0), x.std(axis=1))
print(x.max(), x.max(axis=0), x.max(axis=1))
print(x.min(), x.min(axis=0), x.min(axis=1))
print(np.median(x), np.median(x, axis=0), np.median(x, axis=1))

2.5 [2. 3.] [1.5 3.5]
10 [4 6] [3 7]
1.118033988749895 [1. 1.] [0.5 0.5]
4 [3 4] [2 4]
1 [1 2] [1 3]
2.5 [2. 3.] [1.5 3.5]


In [138]:
# 6.3
x = np.ones((4, 4)) * np.arange(1, 5)
print(x)

[[1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]]
